### ISSUE TITLE
Wrong enhanced checksum

### ISSUE THREAD

**Issue by SteB8Pro** [MarkusLange/Teensy_3.x_LIN_Master#6]
Hello, I think I found a mistake. From the information I found on the LIN 2.x standard, the enhanced checksum should be calculated using the protected id and not the raw id. I fixed the issue replacing PID with send_pid in line 424 of lin_bus.cpp. I hope this information can be helpful.

**Comment by MarkusLange** [comment]
Oh yes you are right
[Link](https://microchipdeveloper.com/lin:protocol-dll-lin-message-frame)
![grafik](https://user-images.githubusercontent.com/1971238/219039194-5ceb1d38-513d-4dcb-94f4-cf9feacdf58a.png)
![grafik](https://user-images.githubusercontent.com/1971238/219039349-3dfdea89-717a-40de-9b7b-6c20ce57bf28.png)
It says the PID not the FID, correct it thank you

**Comment by MarkusLange** [comment]
Closed thanks
