### ISSUE TITLE
LIN Break Limitation

### ISSUE THREAD

**Issue by trollkno1l** [MarkusLange/Teensy_3.x_LIN_Master#8]
Hi!

what is the reason there is a limitation of possible breakbits for configurating LIN Master?
And why is it different with the teensy model used?

Because I would need more breakbits for my application...
Guess it has to with UART, but cant tell why and how to fix it.

![image](https://github.com/MarkusLange/Teensy_3.x_4.x_and_LC_LIN_Master/assets/125410473/c32e5870-8d5c-44f0-8679-27638cb3738e)

**Comment by MarkusLange** [comment]
Hi,

yes this limitations are on the Hardware side, differences are based on the controller it self you can try to emulate more breakbits with an pulldown and an delay, and use after it the Uart in the normal way
